### ISSUE TITLE
Max open file handle limit reached

### ISSUE THREAD

**Issue by rsitzman** [128technology/influx-importer#1]
While collecting data from a conductor instance with 5 routers connected I started getting the following errors:

```
Influx write for total_data(router=router-01,service_class=MultimediaStreaming) failed return successfully: Post http://127.0.0.1:8086/write?consistency=&db=analytics&precision=ms&rp=: dial tcp 127.0.0.1:8086: socket: too many open files
Influx write for rx_data(router=router-01,service_class=MultimediaStreaming) failed return successfully: Post http://127.0.0.1:8086/write?consistency=&db=analytics&precision=ms&rp=: dial tcp 127.0.0.1:8086: socket: too many open files
```

ulimit reported the max number of open files = 1024, increasing this to 2048 allowed the collector to complete successfully.

**Comment by thedillonb** [comment]
@rsitzman, have you seen this with the latest importer? I haven't been able to reproduce this for a while so I think I might have inadvertently squashed this at some point.

**Comment by rsitzman** [comment]
I'm not seeing the error anymore either, looks like you got it. 👍

**Comment by rsitzman** [comment]
I'm not seeing the error anymore either, looks like you got it. 👍
